### PR TITLE
add new collection NODEBIRDS

### PR DESCRIPTION
**Pull request by ArtByCitySlava**
add new collection NODEBIRDS

### CODE REVIEW

**Comment by Demon-devil** [comment]
The value of the slug field in the meta.json file needs to be consistent with the folder name, and the case must be consistent. Please modify it. thanks

**Comment by ArtByCitySlava** [comment]
can it be all caps or lowercase is best? Thank you

**Comment by ArtByCitySlava** [comment]
> The value of the slug field in the meta.json file needs to be consistent with the folder name, and the case must be consistent. Please modify it. thanks

Can it be all caps or lowercase is best? Thank you

**Comment by ArtByCitySlava** [comment]
> The value of the slug field in the meta.json file needs to be consistent with the folder name, and the case must be consistent. Please modify it. thanks

Done, new changes made. Thank you

**Pull request closed without merging**
