### PR TITLE
DUMMY GIRL

### PR DESCRIPTION
**Pull request by rose135666**
[inscriptions.json](https://github.com/okx/ordinals-collections/files/13823299/inscriptions.json)
[meta (2).json](https://github.com/okx/ordinals-collections/files/13823300/meta.2.json)

### CODE REVIEW

**Comment by rose135666** [comment]
please change the twitter it isnt the correct one

**Comment by rose135666** [comment]
https://twitter.com/dummygirlNFT  these is what i added please check

**Comment by rose135666** [comment]
please the twitter

**Comment by rose135666** [comment]
https://twitter.com/dummygirlNFT

**Review by rose135666 — COMMENTED** [review]
[Uploading meta (2).json…]()

**Comment by Demon-devil** [comment]
Please refer to the link below to submit content, thanks, [https://docs.google.com/document/d/1omEZx6mhyVoOlurqJwAnVZcWVkc-LbO0d8G_ZgR_T60/edit?usp=sharing]

**Pull request closed without merging**
